import forms from "@tailwindcss/forms";
import containerQueries from "@tailwindcss/container-queries";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#edb1ff",
        "on-background": "#e5e2e3",
        "surface-container": "#201f20",
        "secondary-container": "#583d5f",
        "on-secondary-fixed-variant": "#583d5f",
        tertiary: "#d6baff",
        "secondary-fixed": "#fad7ff",
        "on-error": "#690005",
        "secondary-fixed-dim": "#debbe4",
        background: "#0D0D0E",
        "on-tertiary-fixed": "#270057",
        "on-primary": "#520070",
        "tertiary-fixed": "#ecdcff",
        "on-primary-fixed": "#320046",
        "on-primary-container": "#fff3fd",
        "tertiary-container": "#835dc0",
        "on-secondary": "#402747",
        primary: "#edb1ff",
        "on-tertiary-container": "#fcf4ff",
        "on-primary-fixed-variant": "#6e208c",
        "inverse-on-surface": "#313031",
        "surface-tint": "#edb1ff",
        "surface-container-lowest": "#0e0e0f",
        "surface-container-high": "#2a2a2b",
        "outline-variant": "#4e4350",
        "on-surface-variant": "#d1c2d2",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e5e2e3",
        "primary-container": "#9d50bb",
        "on-secondary-container": "#ccaad2",
        "surface-bright": "#3a393a",
        "surface-container-low": "#1c1b1c",
        "surface-variant": "#353436",
        "on-secondary-fixed": "#291231",
        "primary-fixed": "#f9d8ff",
        outline: "#9a8c9b",
        error: "#ffb4ab",
        "tertiary-fixed-dim": "#d6baff",
        "on-surface": "#e5e2e3",
        "error-container": "#93000a",
        surface: "#131314",
        "on-tertiary": "#40147a",
        "surface-dim": "#131314",
        "surface-container-highest": "#353436",
        secondary: "#debbe4",
        "on-tertiary-fixed-variant": "#573092",
        "inverse-primary": "#883ca6",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-mobile": "20px",
        unit: "8px",
        "margin-desktop": "80px",
        "container-max": "1440px",
        gutter: "24px",
      },
      fontFamily: {
        "display-lg-mobile": ["Playfair Display"],
        "body-lg": ["Plus Jakarta Sans"],
        "display-lg": ["Playfair Display"],
        "label-md": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-sm": ["Playfair Display"],
        "label-sm": ["Plus Jakarta Sans"],
        "headline-md": ["Playfair Display"],
      },
      fontSize: {
        "display-lg-mobile": [
          "40px",
          {
            lineHeight: "48px",
            letterSpacing: "-0.01em",
            fontWeight: "700",
          },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-lg": [
          "84px",
          {
            lineHeight: "92px",
            letterSpacing: "-0.02em",
            fontWeight: "700",
          },
        ],
        "label-md": [
          "14px",
          {
            lineHeight: "20px",
            letterSpacing: "0.05em",
            fontWeight: "600",
          },
        ],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "600" }],
      },
    },
  },
  plugins: [forms, containerQueries],
};
